# Generated by Django 2.2.24 on 2023-04-30 02:06

from django.db import migrations
from django.db.models import Q


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats_without_new_building = Flat.objects.filter(new_building=None)
    flats_without_new_building.filter(construction_year__gte=2015).update(new_building=True)
    flats_without_new_building.filter(construction_year__lt=2015).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building)
    ]