# Generated by Django 2.2.24 on 2023-04-30 16:28

from django.db import migrations

import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = flat.owners_phonenumber
        parsed_number = phonenumbers.parse(phone_number, "RU")
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = f'+7{parsed_number.national_number}'
            flat.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20230430_1804'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number)
    ]
